### ISSUE TITLE
I am a novice at Python, and when I was using the command `pip install cmeel-boost`, a `bootstrap.sh` script popped up for editing. After I closed it, this error occurred. My environment is Python==3.9.

### ISSUE THREAD

**Issue by SparKgod1** [cmake-wheel/cmeel-boost#15]
(dexycb) C:\Users\LENOVO>pip install cmeel-boost
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting cmeel-boost
  Using cached http://mirrors.aliyun.com/pypi/packages/31/94/b348863cdc049ff332d6a7bf1cf76a79e6e3cbac9a06396387fab247b1b4/cmeel_boost-1.84.0.tar.gz (3.6 kB)
  Installing build dependencies ... canceled
ERROR: Operation cancelled by user

(dexycb) C:\Users\LENOVO>pip install cmeel-boost
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting cmeel-boost
  Using cached http://mirrors.aliyun.com/pypi/packages/31/94/b348863cdc049ff332d6a7bf1cf76a79e6e3cbac9a06396387fab247b1b4/cmeel_boost-1.84.0.tar.gz (3.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [177 lines of output]
      -- Building for: Visual Studio 17 2022
      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
      -- The C compiler identification is MSVC 19.39.33523.0
      -- The CXX compiler identification is MSVC 19.39.33523.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: E:/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: E:/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Python3: D:\miniconda3\envs\dexycb\python.exe (found version "3.9.19") found components: Interpreter Development.Module
      -- CONFIGURE_COMMAND: ./bootstrap.sh;--prefix=C:/Users/LENOVO/AppData/Local/Temp/cmeel-ipr5e4q8/whl/cmeel.prefix
      -- BUILD_COMMAND: ./b2;hardcode-dll-paths=true;dll-path='$ORIGIN';link=shared;python=3.9
      -- Configuring done (11.5s)
      -- Generating done (0.1s)
      CMake Warning:
        Manually-specified variables were not used by the project:

          BUILD_TESTING
          Boost_NO_WARN_NEW_VERSIONS
          CMAKE_APPLE_SILICON_PROCESSOR
          CMAKE_INSTALL_LIBDIR
          CMEEL_JOBS
          PYTHON_SITELIB

      -- Build files have been written to: C:/Users/LENOVO/AppData/Local/Temp/cmeel-ipr5e4q8/bld
      适用于 .NET Framework MSBuild 版本 17.9.8+b34f75857

      E:\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: 中间目录或输出目录无法驻留在临时目录下，因为这可能会导致增量生成出现问题。 [C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\ZERO_CHECK.vcxproj]
        1>Checking Build System
      E:\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: 中间目录或输出目录无法驻留在临时目录下，因为这可能会导致增量生成出现问题。 [C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\boost.vcxproj]
        Creating directories for 'boost'
        Building Custom Rule C:/Users/LENOVO/AppData/Local/Temp/pip-install-k4_kab__/cmeel-boost_ebb822057dab454d82ab1c4a4793f8ff/CMakeLists.txt
        Performing download step (download, verify and extract) for 'boost'
        -- Downloading...
           dst='C:/Users/LENOVO/AppData/Local/Temp/cmeel-ipr5e4q8/bld/boost-prefix/src/boost_1_84_0.tar.bz2'
           timeout='none'
           inactivity timeout='none'
        -- Using src='https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2'
        -- [download 0% complete]
        -- [download 1% complete]
        -- [download 2% complete]
        -- [download 3% complete]
        -- [download 4% complete]
        -- [download 5% complete]
        -- [download 6% complete]
        -- [download 7% complete]
        -- [download 8% complete]
        -- [download 9% complete]
        -- [download 10% complete]
        -- [download 11% complete]
        -- [download 12% complete]
        -- [download 13% complete]
        -- [download 14% complete]
        -- [download 15% complete]
        -- [download 16% complete]
        -- [download 17% complete]
        -- [download 18% complete]
        -- [download 19% complete]
        -- [download 20% complete]
        -- [download 21% complete]
        -- [download 22% complete]
        -- [download 23% complete]
        -- [download 24% complete]
        -- [download 25% complete]
        -- [download 26% complete]
        -- [download 27% complete]
        -- [download 28% complete]
        -- [download 29% complete]
        -- [download 30% complete]
        -- [download 31% complete]
        -- [download 32% complete]
        -- [download 33% complete]
        -- [download 34% complete]
        -- [download 35% complete]
        -- [download 36% complete]
        -- [download 37% complete]
        -- [download 38% complete]
        -- [download 39% complete]
        -- [download 40% complete]
        -- [download 41% complete]
        -- [download 42% complete]
        -- [download 43% complete]
        -- [download 44% complete]
        -- [download 45% complete]
        -- [download 46% complete]
        -- [download 47% complete]
        -- [download 48% complete]
        -- [download 49% complete]
        -- [download 50% complete]
        -- [download 51% complete]
        -- [download 52% complete]
        -- [download 53% complete]
        -- [download 54% complete]
        -- [download 55% complete]
        -- [download 56% complete]
        -- [download 57% complete]
        -- [download 58% complete]
        -- [download 59% complete]
        -- [download 60% complete]
        -- [download 61% complete]
        -- [download 62% complete]
        -- [download 63% complete]
        -- [download 64% complete]
        -- [download 65% complete]
        -- [download 66% complete]
        -- [download 67% complete]
        -- [download 68% complete]
        -- [download 69% complete]
        -- [download 70% complete]
        -- [download 71% complete]
        -- [download 72% complete]
        -- [download 73% complete]
        -- [download 74% complete]
        -- [download 75% complete]
        -- [download 76% complete]
        -- [download 77% complete]
        -- [download 78% complete]
        -- [download 79% complete]
        -- [download 80% complete]
        -- [download 81% complete]
        -- [download 82% complete]
        -- [download 83% complete]
        -- [download 84% complete]
        -- [download 85% complete]
        -- [download 86% complete]
        -- [download 87% complete]
        -- [download 88% complete]
        -- [download 89% complete]
        -- [download 90% complete]
        -- [download 91% complete]
        -- [download 92% complete]
        -- [download 93% complete]
        -- [download 94% complete]
        -- [download 95% complete]
        -- [download 96% complete]
        -- [download 97% complete]
        -- [download 98% complete]
        -- [download 99% complete]
        -- [download 100% complete]
        -- verifying file...
               file='C:/Users/LENOVO/AppData/Local/Temp/cmeel-ipr5e4q8/bld/boost-prefix/src/boost_1_84_0.tar.bz2'
        -- Downloading... done
        -- extracting...
             src='C:/Users/LENOVO/AppData/Local/Temp/cmeel-ipr5e4q8/bld/boost-prefix/src/boost_1_84_0.tar.bz2'
             dst='C:/Users/LENOVO/AppData/Local/Temp/cmeel-ipr5e4q8/bld/boost-prefix/src/boost'
        -- extracting... [tar xfz]
        -- extracting... [analysis]
        -- extracting... [rename]
        -- extracting... [clean up]
        -- extracting... done
        No update step for 'boost'
        No patch step for 'boost'
        Performing configure step for 'boost'
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        FileNotFoundError: [Errno 2] No such file or directory: 'project-config.jam'
      E:\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: “C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-mkdir.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-download.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-update.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-patch.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-configure.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-build.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\ced96457f3cfe2edeefa56c54f9eadd1\boost-install.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\b76c64a66d01a237fa04b55913d7f6bc\boost-complete.rule;C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\CMakeFiles\7666a6f0bd602cdd3ea7b5b7cf8f885e\boost.rule;C:\Users\LENOVO\AppData\Local\Temp\pip-install-k4_kab__\cmeel-boost_ebb822057dab454d82ab1c4a4793f8ff\CMakeLists.txt”的自定义生成已退出，代码为 1。 [C:\Users\LENOVO\AppData\Local\Temp\cmeel-ipr5e4q8\bld\boost.vcxproj]
      Traceback (most recent call last):
        File "D:\miniconda3\envs\dexycb\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\miniconda3\envs\dexycb\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\miniconda3\envs\dexycb\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-zi6st1cq\overlay\Lib\site-packages\cmeel\build.py", line 26, in build_wheel
          return build_impl(wheel_directory, editable=False)
        File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-zi6st1cq\overlay\Lib\site-packages\cmeel\impl.py", line 105, in build_impl
          check_call(build_cmd)
        File "D:\miniconda3\envs\dexycb\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', 'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\cmeel-ipr5e4q8\\bld', '-j4']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SparKgod1** [comment]
could i have some help,thanks a lot

**Comment by nim65s** [comment]
Windows is not supported at the moment, sorry for that.

**Comment by SparKgod1** [comment]
Thanks for your reply!I will use linux next time.
