### ISSUE TITLE
issue on pip install cmeel-boost

### ISSUE THREAD

**Issue by SparKgod1** [cmake-wheel/cmeel-boost#16]
sorry to bother again,i sucessfully installed cmeel-boost in my ubuntu 20.04,but when i change to install in ubuntu 18.04 it comes an error, error info as follows,it's too long that i cant find the problem,hope for your help,thanks
`./boost/unordered/unordered_map.hpp:2238:20: error: ‘move’ is not a member of ‘std’
                 alloc_ = std::move(n.alloc_);
                          ^
      ./boost/unordered/unordered_map.hpp:2238:20: note: suggested alternative:
      In file included from ./boost/smart_ptr/make_shared_object.hpp:17:0,
                       from ./boost/smart_ptr/make_shared.hpp:15,
                       from ./boost/make_shared.hpp:14,
                       from ./boost/smart_ptr.hpp:24,
                       from ./boost/property_map/dynamic_property_map.hpp:30,
                       from libs/graph/src/read_graphviz_new.cpp:32:
      ./boost/move/utility_core.hpp:77:10: note:   ‘boost::move’
                move(rv<T>& x) BOOST_NOEXCEPT
                ^
      In file included from ./boost/unordered_map.hpp:17:0,
                       from ./boost/pending/container_traits.hpp:24,
                       from ./boost/graph/named_graph.hpp:23,
                       from ./boost/graph/adjacency_list.hpp:36,
                       from ./boost/graph/graphviz.hpp:24,
                       from libs/graph/src/read_graphviz_new.cpp:49:
      ./boost/unordered/unordered_map.hpp:2238:30: error: ‘n’ was not declared in this scope
                 alloc_ = std::move(n.alloc_);
                                    ^
      ./boost/unordered/unordered_map.hpp:2240:16: error: ‘n’ was not declared in this scope
               ptr_ = n.ptr_;
                      ^
      ./boost/unordered/unordered_map.hpp: In member function ‘int boost::unordered::node_handle_map<N, K, T, A>::noexcept(int)’:
      ./boost/unordered/unordered_map.hpp:2279:37: error: ‘n’ was not declared in this scope
                   !alloc_.has_value() || !n.alloc_.has_value()) {
                                           ^
      ./boost/unordered/unordered_map.hpp:2282:40: error: ‘n’ was not declared in this scope
               boost::core::invoke_swap(ptr_, n.ptr_);
                                              ^
      ./boost/unordered/unordered_map.hpp:2283:7: warning: no return statement in function returning non-void [-Wreturn-type]
             }
             ^
      ./boost/unordered/unordered_map.hpp: At global scope:
      ./boost/unordered/unordered_map.hpp:2288:7: error: expected initializer before ‘noexcept’
             noexcept(noexcept(x.swap(y)))
             ^
      ./boost/unordered/unordered_map.hpp:2301:63: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
             insert_return_type_map(insert_return_type_map const&) = delete;
                                                                     ^
      ./boost/unordered/unordered_map.hpp:2302:74: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
             insert_return_type_map& operator=(insert_return_type_map const&) = delete;
                                                                                ^
      ./boost/unordered/unordered_map.hpp:2304:52: error: expected ‘,’ or ‘...’ before ‘&&’ token
             insert_return_type_map(insert_return_type_map&& x) noexcept
                                                          ^
      ./boost/unordered/unordered_map.hpp:2304:56: error: invalid constructor; you probably meant ‘boost::unordered::insert_return_type_map<Iter, NodeType> (const boost::unordered::insert_return_type_map<Iter, NodeType>&)’
             insert_return_type_map(insert_return_type_map&& x) noexcept
                                                              ^
      ./boost/unordered/unordered_map.hpp:2304:56: error: expected ‘;’ at end of member declaration
      ./boost/unordered/unordered_map.hpp:2304:58: error: ‘noexcept’ does not name a type
             insert_return_type_map(insert_return_type_map&& x) noexcept
                                                                ^
      ./boost/unordered/unordered_map.hpp:2304:58: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
      ./boost/unordered/unordered_map.hpp:2311:63: error: expected ‘,’ or ‘...’ before ‘&&’ token
             insert_return_type_map& operator=(insert_return_type_map&& x)
                                                                     ^
      ./boost/unordered/unordered_map.hpp: In member function ‘boost::unordered::insert_return_type_map<Iter, NodeType>& boost::unordered::insert_return_type_map<Iter, NodeType>::operator=(boost::unordered::insert_return_type_map<Iter, NodeType>)’:
      ./boost/unordered/unordered_map.hpp:2313:20: error: ‘x’ was not declared in this scope
               inserted = x.inserted;
                          ^
      ./boost/unordered/unordered_map.hpp:2315:16: error: ‘move’ is not a member of ‘std’
               node = std::move(x.node);
                      ^
      ./boost/unordered/unordered_map.hpp:2315:16: note: suggested alternative:
      In file included from ./boost/smart_ptr/make_shared_object.hpp:17:0,
                       from ./boost/smart_ptr/make_shared.hpp:15,
                       from ./boost/make_shared.hpp:14,
                       from ./boost/smart_ptr.hpp:24,
                       from ./boost/property_map/dynamic_property_map.hpp:30,
                       from libs/graph/src/read_graphviz_new.cpp:32:
      ./boost/move/utility_core.hpp:77:10: note:   ‘boost::move’
                move(rv<T>& x) BOOST_NOEXCEPT
                ^
      In file included from ./boost/typeof/typeof.hpp:20:0,
                       from ./boost/graph/buffer_concepts.hpp:10,
                       from ./boost/graph/graph_concepts.hpp:21,
                       from ./boost/graph/detail/adjacency_list.hpp:33,
                       from ./boost/graph/adjacency_list.hpp:255,
                       from ./boost/graph/graphviz.hpp:24,
                       from libs/graph/src/read_graphviz_new.cpp:49:
      ./boost/typeof/decltype.hpp: At global scope:
      ./boost/typeof/decltype.hpp:13:5: error: expected unqualified-id before ‘using’
           using remove_cv_ref_t = typename std::remove_cv<typename std::remove_reference<T>::type>::type;
           ^
      In file included from ./boost/xpressive/detail/core/adaptor.hpp:17:0,
                       from ./boost/xpressive/detail/core/matcher/regex_byref_matcher.hpp:25,
                       from ./boost/xpressive/detail/core/matchers.hpp:41,
                       from ./boost/xpressive/regex_primitives.hpp:22,
                       from ./boost/xpressive/xpressive_static.hpp:24,
                       from ./boost/graph/graphviz.hpp:35,
                       from libs/graph/src/read_graphviz_new.cpp:49:
      ./boost/implicit_cast.hpp:31:1: error: ‘constexpr’ does not name a type
       constexpr T implicit_cast (typename boost::detail::icast_identity<T>::type x) {
       ^
      ./boost/implicit_cast.hpp:31:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
      In file included from ./boost/xpressive/detail/core/matcher/regex_byref_matcher.hpp:25:0,
                       from ./boost/xpressive/detail/core/matchers.hpp:41,
                       from ./boost/xpressive/regex_primitives.hpp:22,
                       from ./boost/xpressive/xpressive_static.hpp:24,
                       from ./boost/graph/graphviz.hpp:35,
                       from libs/graph/src/read_graphviz_new.cpp:49:
      ./boost/xpressive/detail/core/adaptor.hpp: In member function ‘virtual bool boost::xpressive::detail::xpression_adaptor<Xpr, Base>::match(boost::xpressive::detail::match_state<typename Base::iterator_type>&) const’:
      ./boost/xpressive/detail/core/adaptor.hpp:52:16: error: ‘implicit_cast’ was not declared in this scope
               return implicit_cast<xpr_type &>(this->xpr_).match(state);
                      ^
      ./boost/xpressive/detail/core/adaptor.hpp:52:39: error: expected primary-expression before ‘&’ token
               return implicit_cast<xpr_type &>(this->xpr_).match(state);
                                             ^
      ./boost/xpressive/detail/core/adaptor.hpp:52:40: error: expected primary-expression before ‘>’ token
               return implicit_cast<xpr_type &>(this->xpr_).match(state);
                                              ^
      In file included from ./boost/lexical_cast/detail/converter_lexical.hpp:50:0,
                       from ./boost/lexical_cast/try_lexical_convert.hpp:45,
                       from ./boost/lexical_cast.hpp:33,
                       from ./boost/property_map/dynamic_property_map.hpp:23,
                       from libs/graph/src/read_graphviz_new.cpp:32:
      ./boost/lexical_cast/detail/converter_lexical_streams.hpp: In instantiation of ‘bool boost::detail::lexical_istream_limited_src<CharT, Traits, RequiresStringbuffer, CharacterBufferSize>::shl_signed(T) [with T = int; CharT = char; Traits = std::char_traits<char>; bool RequiresStringbuffer = false; long unsigned int CharacterBufferSize = 21ul]’:
      ./boost/lexical_cast/detail/converter_lexical_streams.hpp:411:76:   required from ‘bool boost::detail::lexical_istream_limited_src<CharT, Traits, RequiresStringbuffer, CharacterBufferSize>::operator<<(int) [with CharT = char; Traits = std::char_traits<char>; bool RequiresStringbuffer = false; long unsigned int CharacterBufferSize = 21ul]’
      ./boost/lexical_cast/detail/converter_lexical.hpp:487:21:   required from ‘static bool boost::detail::lexical_converter_impl<Target, Source>::try_convert(const Source&, Target&) [with Target = std::__cxx11::basic_string<char>; Source = int]’
      ./boost/lexical_cast/try_lexical_convert.hpp:201:44:   required from ‘bool boost::conversion::detail::try_lexical_convert(const Source&, Target&) [with Target = std::__cxx11::basic_string<char>; Source = int]’
      ./boost/lexical_cast.hpp:42:60:   required from ‘Target boost::lexical_cast(const Source&) [with Target = std::__cxx11::basic_string<char>; Source = int]’
      libs/graph/src/read_graphviz_new.cpp:785:69:   required from here
      ./boost/lexical_cast/detail/converter_lexical_streams.hpp:269:94: error: ‘lcast_to_unsigned’ was not declared in this scope
                       CharT* tmp_start = lcast_put_unsigned<Traits, utype, CharT>(lcast_to_unsigned(n), tmp_finish).convert();
                                                                                                    ^
      
          "g++"   -fvisibility-inlines-hidden -fPIC -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden  -DBOOST_ALL_NO_LIB=1 -DBOOST_COBALT_USE_STD_PMR=1 -DBOOST_GRAPH_DYN_LINK=1 -DNDEBUG   -I"." -I"libs/graph/src"  -c -o "bin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden/read_graphviz_new.o" "libs/graph/src/read_graphviz_new.cpp"
      
      ...failed gcc.compile.c++ bin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden/read_graphviz_new.o...
      ...skipped <pbin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden>libboost_graph.so.1.84.0 for lack of <pbin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden>read_graphviz_new.o...
      ...skipped <p/tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib>libboost_graph.so.1.84.0 for lack of <pbin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden>libboost_graph.so.1.84.0...
      ...skipped <p/tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib>libboost_graph.so for lack of <p/tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib>libboost_graph.so.1.84.0...
      ...skipped <pbin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden>libboost_graph-variant-shared.cmake for lack of <pbin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden>libboost_graph.so.1.84.0...
      ...skipped <p/tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib/cmake/boost_graph-1.84.0>libboost_graph-variant-shared.cmake for lack of <pbin.v2/libs/graph/build/gcc-5/release/threading-multi/visibility-hidden>libboost_graph-variant-shared.cmake...
      gcc.compile.c++ bin.v2/libs/test/build/gcc-5/release/link-static/threading-multi/visibility-hidden/unit_test_parameters.o
      In file included from ./boost/smart_ptr/shared_ptr.hpp:17:0,
                       from ./boost/shared_ptr.hpp:17,
                       from ./boost/test/utils/runtime/fwd.hpp:24,
                       from ./boost/test/utils/runtime/argument.hpp:19,
                       from ./boost/test/unit_test_parameters.hpp:19,
                       from ./boost/test/impl/unit_test_parameters.ipp:22,
                       from libs/test/src/unit_test_parameters.cpp:16:
      ./boost/smart_ptr/detail/requires_cxx11.hpp:19:106: note: #pragma message: C++03 support was deprecated in Boost.SmartPtr 1.82 and will be removed in Boost.SmartPtr 1.85.
       BOOST_PRAGMA_MESSAGE("C++03 support was deprecated in Boost.SmartPtr 1.82 and will be removed in Boost.SmartPtr 1.85.")
                                                                                                                ^
      In file included from ./boost/function/detail/prologue.hpp:12:0,
                       from ./boost/function/function_template.hpp:13,
                       from ./boost/function/detail/maybe_include.hpp:15,
                       from ./boost/function/function0.hpp:11,
                       from ./boost/test/unit_test_parameters.hpp:23,
                       from ./boost/test/impl/unit_test_parameters.ipp:22,
                       from libs/test/src/unit_test_parameters.cpp:16:
      ./boost/function/detail/requires_cxx11.hpp:18:106: note: #pragma message: C++03 support was deprecated in Boost.Function 1.82 and will be removed in Boost.Function 1.85.
       BOOST_PRAGMA_MESSAGE("C++03 support was deprecated in Boost.Function 1.82 and will be removed in Boost.Function 1.85.")
                                                                                                                ^
      In file included from ./boost/bind/mem_fn.hpp:24:0,
                       from ./boost/mem_fn.hpp:22,
                       from ./boost/function/detail/prologue.hpp:19,
                       from ./boost/function/function_template.hpp:13,
                       from ./boost/function/detail/maybe_include.hpp:15,
                       from ./boost/function/function0.hpp:11,
                       from ./boost/test/unit_test_parameters.hpp:23,
                       from ./boost/test/impl/unit_test_parameters.ipp:22,
                       from libs/test/src/unit_test_parameters.cpp:16:
      ./boost/bind/detail/requires_cxx11.hpp:18:98: note: #pragma message: C++03 support was deprecated in Boost.Bind 1.82 and will be removed in Boost.Bind 1.85.
       BOOST_PRAGMA_MESSAGE("C++03 support was deprecated in Boost.Bind 1.82 and will be removed in Boost.Bind 1.85.")
                                                                                                        ^
      gcc.archive bin.v2/libs/test/build/gcc-5/release/link-static/threading-multi/visibility-hidden/libboost_test_exec_monitor.a
      boost-install.generate-cmake-variant- bin.v2/libs/test/build/gcc-5/release/threading-multi/visibility-hidden/libboost_test_exec_monitor-variant-shared.cmake
      common.copy /tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib/libboost_test_exec_monitor.a
      common.copy /tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib/cmake/boost_test_exec_monitor-1.84.0/libboost_test_exec_monitor-variant-shared.cmake
      gcc.compile.c++ bin.v2/libs/test/build/gcc-5/release/threading-multi/visibility-hidden/unit_test_parameters.o
      In file included from ./boost/smart_ptr/shared_ptr.hpp:17:0,
                       from ./boost/shared_ptr.hpp:17,
                       from ./boost/test/utils/runtime/fwd.hpp:24,
                       from ./boost/test/utils/runtime/argument.hpp:19,
                       from ./boost/test/unit_test_parameters.hpp:19,
                       from ./boost/test/impl/unit_test_parameters.ipp:22,
                       from libs/test/src/unit_test_parameters.cpp:16:
      ./boost/smart_ptr/detail/requires_cxx11.hpp:19:106: note: #pragma message: C++03 support was deprecated in Boost.SmartPtr 1.82 and will be removed in Boost.SmartPtr 1.85.
       BOOST_PRAGMA_MESSAGE("C++03 support was deprecated in Boost.SmartPtr 1.82 and will be removed in Boost.SmartPtr 1.85.")
                                                                                                                ^
      In file included from ./boost/function/detail/prologue.hpp:12:0,
                       from ./boost/function/function_template.hpp:13,
                       from ./boost/function/detail/maybe_include.hpp:15,
                       from ./boost/function/function0.hpp:11,
                       from ./boost/test/unit_test_parameters.hpp:23,
                       from ./boost/test/impl/unit_test_parameters.ipp:22,
                       from libs/test/src/unit_test_parameters.cpp:16:
      ./boost/function/detail/requires_cxx11.hpp:18:106: note: #pragma message: C++03 support was deprecated in Boost.Function 1.82 and will be removed in Boost.Function 1.85.
       BOOST_PRAGMA_MESSAGE("C++03 support was deprecated in Boost.Function 1.82 and will be removed in Boost.Function 1.85.")
                                                                                                                ^
      In file included from ./boost/bind/mem_fn.hpp:24:0,
                       from ./boost/mem_fn.hpp:22,
                       from ./boost/function/detail/prologue.hpp:19,
                       from ./boost/function/function_template.hpp:13,
                       from ./boost/function/detail/maybe_include.hpp:15,
                       from ./boost/function/function0.hpp:11,
                       from ./boost/test/unit_test_parameters.hpp:23,
                       from ./boost/test/impl/unit_test_parameters.ipp:22,
                       from libs/test/src/unit_test_parameters.cpp:16:
      ./boost/bind/detail/requires_cxx11.hpp:18:98: note: #pragma message: C++03 support was deprecated in Boost.Bind 1.82 and will be removed in Boost.Bind 1.85.
       BOOST_PRAGMA_MESSAGE("C++03 support was deprecated in Boost.Bind 1.82 and will be removed in Boost.Bind 1.85.")
                                                                                                        ^
      gcc.link.dll bin.v2/libs/test/build/gcc-5/release/threading-multi/visibility-hidden/libboost_unit_test_framework.so.1.84.0
      boost-install.generate-cmake-variant- bin.v2/libs/test/build/gcc-5/release/threading-multi/visibility-hidden/libboost_unit_test_framework-variant-shared.cmake
      common.copy /tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib/libboost_unit_test_framework.so.1.84.0
      common.copy /tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib/cmake/boost_unit_test_framework-1.84.0/libboost_unit_test_framework-variant-shared.cmake
      ln-UNIX /tmp/cmeel-d19e9g4k/bld/boost-prefix/src/boost/stage/lib/libboost_unit_test_framework.so
      ...failed updating 44 targets...
      ...skipped 35 targets...
      ...updated 450 targets...
      CMakeFiles/boost.dir/build.make:85: recipe for target 'boost-prefix/src/boost-stamp/boost-build' failed
      make[2]: *** [boost-prefix/src/boost-stamp/boost-build] Error 1
      CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/boost.dir/all' failed
      make[1]: *** [CMakeFiles/boost.dir/all] Error 2
      Makefile:135: recipe for target 'all' failed
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "/home/lvxuan/.conda/envs/lvxuan_retargeting/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lvxuan/.conda/envs/lvxuan_retargeting/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/lvxuan/.conda/envs/lvxuan_retargeting/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-o4uvdo7y/overlay/lib/python3.8/site-packages/cmeel/build.py", line 26, in build_wheel
          return build_impl(wheel_directory, editable=False)
        File "/tmp/pip-build-env-o4uvdo7y/overlay/lib/python3.8/site-packages/cmeel/impl.py", line 105, in build_impl
          check_call(build_cmd)
        File "/home/lvxuan/.conda/envs/lvxuan_retargeting/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '/tmp/cmeel-d19e9g4k/bld', '-j4']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by SparKgod1** [comment]
my python version is 3.8.19,and pip version is 24.0

**Comment by SparKgod1** [comment]
i find that my gcc version is 9.4.0,but my g++ version is 5.4.0,is this the root of the problem?

**Comment by SparKgod1** [comment]
in my ubuntu 18.04 ,I am unable to access boost.org because I am in China and do not have a proxy in this server, is that the problem？

**Comment by nim65s** [comment]
Hi @SparKgod1, 
Could you tell me more about your use case ?

The cmeel project is mostly here to provide pre-built binaries through PyPI, so most of the time, if you see anything compiling, that's an issue.

Ubuntu 18.04 is too old to use the pre-built binaries, as they are made with manylinux_2_28, so you'll need a linux with glibc >= 2.28, and Ubuntu 18.04 has glibc 2.27.

18.04 is not supported by canonical anymore, so you should really consider stop using it and upgrade your 18.04 systems if you still have any.

If you really need support for that system, I'll probably be able to recommand another package management strategy, but for this I need to know more about your use case.

**Comment by BIT-wh** [comment]
sorry to bother, cmeel-boost can be installed in win11? I have a problem in installing it.

**Comment by nim65s** [comment]
@BIT-wh : no. And please don't ask this in an unrelated issue.

**Comment by SparKgod1** [comment]
> Hi @SparKgod1, Could you tell me more about your use case ?
> 
> The cmeel project is mostly here to provide pre-built binaries through PyPI, so most of the time, if you see anything compiling, that's an issue.
> 
> Ubuntu 18.04 is too old to use the pre-built binaries, as they are made with manylinux_2_28, so you'll need a linux with glibc >= 2.28, and Ubuntu 18.04 has glibc 2.27.
> 
> 18.04 is not supported by canonical anymore, so you should really consider stop using it and upgrade your 18.04 systems if you still have any.
> 
> If you really need support for that system, I'll probably be able to recommand another package management strategy, but for this I need to know more about your use case.

Thanks for your Patient reply,actually,I’m using [dex_retargeting](https://github.com/dexsuite/dex-retargeting).I'll appreciate it if you could offer me a package management strategy,thanks a lot.

**Comment by SparKgod1** [comment]
seem dex_retargeting depend pin==2.7.0

**Comment by nim65s** [comment]
The best solution is to upgrade this 18.04 to 20.04, 22.04, or 24.04, by far. 

If you really can't, as you already have conda, you can install pinocchio from conda instead of pip. you'll have to remove this `pin==2.7.0` dependency in dex_retargeting before installing it.
