### ISSUE TITLE
Boost filesystem symbol not found (macos-latest, python-3.8)

### ISSUE THREAD

**Issue by stephane-caron** [cmake-wheel/cmeel-boost#9]
After the update following https://github.com/cmake-wheel/cmeel-boost/issues/6 I've re-run the failed jobs in the `macos-latest` `python-3.8` pipeline of Pink. They end up with a different error on a boost-filesystem symbol not found:

```
   ======================================================================
  Error: ERROR: pink (unittest.loader._FailedTest)
  ----------------------------------------------------------------------
  ImportError: Failed to import test module: pink
  Traceback (most recent call last):
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 470, in _find_test_path
      package = self._get_module_from_name(name)
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
      __import__(name)
    File "/Users/runner/work/pink/pink/pink/__init__.py", line 20, in <module>
      from .configuration import Configuration
    File "/Users/runner/work/pink/pink/pink/configuration.py", line 28, in <module>
      import pinocchio as pin
    File "/Users/runner/work/pink/pink/.tox/py38/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
      from .pinocchio_pywrap import *
  ImportError: dlopen(/Users/runner/work/pink/pink/.tox/py38/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/pinocchio_pywrap.cpython-38-darwin.so, 0x0002): Symbol not found: (__ZN5boost10filesystem4path9append_v3EPKcS3_)
    Referenced from: '/Users/runner/work/pink/pink/.tox/py38/lib/python3.8/site-packages/cmeel.prefix/lib/libpinocchio.dylib'
    Expected in: '/Users/runner/work/pink/pink/.tox/py38/lib/python3.8/site-packages/cmeel.prefix/lib/libboost_filesystem.dylib'
```

**Comment by stephane-caron** [comment]
Aaaand it was likely a matter of waiting for caches to refresh. I re-run the pipeline tonight and now it passes :+1:
